---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        timestamp: "1583398841"
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 60
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 60

---
# NodePort
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP

# LoadBalancer
# only 1 AZ is added:
# - https://github.com/kubernetes/kubernetes/issues/28586
# - https://github.com/kubernetes/kubernetes/issues/74527
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
# spec:
#   selector:
#     app: nginx
#   type: LoadBalancer
#   ports:
#     - name: http
#       port: 80
#       targetPort: 80
#       protocol: TCP
